baseurl = "http://kynean.com/"
publishdir = "./dist"
languageCode = "en-us"
title = "Kynean"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]
    # information about you and your website for search engines.
    name = "Kynean"
    description = "Awesomeness at your fingertips."

    # The path must be relative to the static folder
    favicon = "favicon.ico"

    # Navigation
    [params.navigation]
        brand = "Kynean"

        [params.navigation.links]
            about     = "About"
            services  = "Services"
            portfolio = ""
            contact   = "Contact"

    # Hero section
    [params.hero]
        # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "Hey there!"
        subtitle   = "Kynean is a collection of apps to make life simple for you!"

        [params.hero.button]
            text = "Read more"
            link = "#about"


    # About section
    [params.about]
        headline    = "We are nerds"
        description = "Doing what we love."

        # [params.about.button]
        #     text  = "Read more"
        #     link  = "#services"

    # Service section
    [params.services]
        headline = "Our offer"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Sturdy Templates"
            description = "Our templates are updated regularly so they don't break."

        [[params.services.list]]
            icon = "fa-paper-plane"
            title = "Ready to Ship"
            description = "You can use this theme as is, or you can make changes!"

        [[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Up to Date"
            description = "We update dependencies to keep things fresh."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Love"
            description = "You have to make your websites with love these days!"

    # Portfolio modals
    [params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
    [params.aside]
        headline = "Like what you see? Have a look at the code, it's open source."

        [params.aside.button]
            icon = "fa-github"
            text = "Source"
            link = "//github.com/kynean"

    # Contact section
    [params.contact]
        headline = "Let's Get In Touch!"
        description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
        email = "hello@kynean.com"

    # Google Maps section
    # [params.location]
    #   latitude  = "34.007850"
    #   longitude = "-118.499305"
    #   maps_api_key = ""
